### ISSUE TITLE
[MEMBER]회원가입 이미지 서버 구축 및 DB URL저장

### ISSUE THREAD

**Issue by maam6073** [codestates-seb/seb41_main_005#16]
### 작업 내용
- 이미지파일 저장을위한 스토리지서버 S3(아마존) 구축
- 회원가입에서 이미지 로직 수정
- DB에 이미지 URL 저장

### 예상 작업 시간
- 3h

**Comment by H-JWANNA** [comment]
AWS 프리티어로 충분한가요..? 돈 쓰시면 안됩니다 ㅠㅠ

**Comment by maam6073** [comment]
일단 테스트 해보겠습니다 ㅜㅜ
