### ISSUE TITLE
회원가입 유효성 검사 정보 공유

### ISSUE THREAD

**Issue by maam6073** [codestates-seb/seb41_main_005#17]
### 작업 내용에 대한 설명
- 회원가입시 이메일,패스워드,닉네임,자기소개 길이에 대한 공유

### 회원가입 유효성 검사 정보
- 1. 이메일 : 공백 X, 이메일 형식 ex)test@test.com
- 2. 비밀번호 : 공백 X, 2자 ~ 20자
- 3. 닉네임 : 공백X,  5자 ~ 16자
- 4. 자기소개 : ~150자

혹시 이상하거나 변경했으면 좋겠는 부분에 대해서 의견 남겨주세요 없으시면 이대로 진행하겠습니다.

**Comment by H-JWANNA** [comment]
닉네임 5글자면 좀 길지 않을까 생각합니다

**Comment by hyob12** [comment]
자기소개 150자로 해주시면 감사하겠습니다

**Comment by maam6073** [comment]
닉네임 2자 ~ 16자
자기소개 150자로 수정하겠습니다 괜찮으실까요?

**Comment by H-JWANNA** [comment]
좋습니다!
